server:
  port: 8082
  servlet:
    context-path: /api/v1
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/Tododb
    username: root
    password: password
